// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsqpkeybuuevycqdixhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzcXBrZXlidXVldnljcWRpeGhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzODU5OTgsImV4cCI6MjA2Njk2MTk5OH0.A8XnTZnW5PGvglx5stGQRZMYB5Le4zmQlW1_h2g3GU4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});